### ISSUE TITLE
Add name field to subscriptions going forward

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#130]
This should be required on new accounts.

**Comment by setphen** [comment]
There is an non-required name field on the Subscription model already, however I think the need here is to be able to search users/subscriptions by the name of the user (rather than their email).

I think it's best to make the name field of the User model required, and then add the ability to search subscriptions based on their User fk (i.e. `search_fields = ['user__name']` in the SubscriptionAdmin)
