### ISSUE TITLE
Ensure renewals will work correctly in Stripe

### ISSUE THREAD

**Issue by cndreisbach** [greentogo/greentogo#131]

**Comment by setphen** [comment]
Renewals are working correctly in stripe, however users who signed up during the time when stripe was handled manually do not have a stripe ID. One solution is to find these users and provide their stripe IDs manually by matching them to subscriptions in stripe (by their email address).

I'm working to collect a list of users who fit in this category.

Otherwise, renewals are working correctly in Stripe, though the webhooks are untested. I'm not sure how to test them, exactly.
